apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: fraudDetectionWorkflowStateStore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: "localhost:6379"
  - name: redisPassword
    value: "your-redis-password"
  - name: actorStateStore
    value: "true"